[2024-07-03T21:34:50.630+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-03T21:34:50.699+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exchange_rate_dag.run_script scheduled__2024-01-19T00:00:00+00:00 [queued]>
[2024-07-03T21:34:50.720+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exchange_rate_dag.run_script scheduled__2024-01-19T00:00:00+00:00 [queued]>
[2024-07-03T21:34:50.723+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-03T21:34:50.758+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_script> on 2024-01-19 00:00:00+00:00
[2024-07-03T21:34:50.780+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=277) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-03T21:34:50.784+0000] {standard_task_runner.py:63} INFO - Started process 286 to run task
[2024-07-03T21:34:50.784+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'exchange_rate_dag', 'run_script', 'scheduled__2024-01-19T00:00:00+00:00', '--job-id', '81', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpbu1xobc4']
[2024-07-03T21:34:50.787+0000] {standard_task_runner.py:91} INFO - Job 81: Subtask run_script
[2024-07-03T21:34:50.903+0000] {task_command.py:426} INFO - Running <TaskInstance: exchange_rate_dag.run_script scheduled__2024-01-19T00:00:00+00:00 [running]> on host 539cd3e7956f
[2024-07-03T21:34:51.150+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='juan_ml' AIRFLOW_CTX_DAG_ID='exchange_rate_dag' AIRFLOW_CTX_TASK_ID='run_script' AIRFLOW_CTX_EXECUTION_DATE='2024-01-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-19T00:00:00+00:00'
[2024-07-03T21:34:51.155+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-03T21:34:51.157+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-03T21:34:51.158+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/my_dag.py", line 18, in main
    if not validate_credentials():
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/modules/validate_credentials.py", line 8, in validate_credentials
    "REDSHIFT_HOST": os.getenv('REDSHIFT_HOST').replace('http://', ''),
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'replace'
[2024-07-03T21:34:51.199+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=exchange_rate_dag, task_id=run_script, run_id=scheduled__2024-01-19T00:00:00+00:00, execution_date=20240119T000000, start_date=20240703T213450, end_date=20240703T213451
[2024-07-03T21:34:51.230+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 81 for task run_script ('NoneType' object has no attribute 'replace'; 286)
[2024-07-03T21:34:51.289+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-03T21:34:51.321+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T21:34:51.325+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
