[2024-07-05T01:29:35.288+0000] {processor.py:161} INFO - Started process (PID=43) to work on /opt/airflow/dags/my_dag.py
[2024-07-05T01:29:35.350+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-07-05T01:29:35.429+0000] {logging_mixin.py:188} INFO - [2024-07-05T01:29:35.419+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-07-05T01:29:45.306+0000] {processor.py:840} INFO - DAG(s) 'exchange_rate_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-07-05T01:29:51.188+0000] {logging_mixin.py:188} INFO - [2024-07-05T01:29:51.186+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-05T01:29:51.373+0000] {logging_mixin.py:188} INFO - [2024-07-05T01:29:51.373+0000] {dag.py:3954} INFO - Setting next_dagrun for exchange_rate_dag to 2024-03-26 00:00:00+00:00, run_after=2024-03-27 00:00:00+00:00
[2024-07-05T01:29:51.535+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 16.423 seconds
[2024-07-05T01:31:02.425+0000] {processor.py:161} INFO - Started process (PID=136) to work on /opt/airflow/dags/my_dag.py
[2024-07-05T01:31:02.433+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-07-05T01:31:02.478+0000] {logging_mixin.py:188} INFO - [2024-07-05T01:31:02.476+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-07-05T01:31:21.284+0000] {processor.py:840} INFO - DAG(s) 'exchange_rate_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-07-05T01:31:21.416+0000] {logging_mixin.py:188} INFO - [2024-07-05T01:31:21.414+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-05T01:31:21.624+0000] {logging_mixin.py:188} INFO - [2024-07-05T01:31:21.623+0000] {dag.py:3954} INFO - Setting next_dagrun for exchange_rate_dag to 2024-03-28 00:00:00+00:00, run_after=2024-03-29 00:00:00+00:00
[2024-07-05T01:31:21.833+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 19.675 seconds
[2024-07-05T01:32:09.263+0000] {processor.py:161} INFO - Started process (PID=185) to work on /opt/airflow/dags/my_dag.py
[2024-07-05T01:32:09.302+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-07-05T01:32:09.391+0000] {logging_mixin.py:188} INFO - [2024-07-05T01:32:09.345+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-07-05T01:32:26.779+0000] {processor.py:840} INFO - DAG(s) 'exchange_rate_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-07-05T01:32:26.907+0000] {logging_mixin.py:188} INFO - [2024-07-05T01:32:26.905+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-05T01:32:27.019+0000] {logging_mixin.py:188} INFO - [2024-07-05T01:32:27.018+0000] {dag.py:3954} INFO - Setting next_dagrun for exchange_rate_dag to 2024-04-08 00:00:00+00:00, run_after=2024-04-09 00:00:00+00:00
[2024-07-05T01:32:27.145+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 18.003 seconds
[2024-07-05T01:33:13.395+0000] {processor.py:161} INFO - Started process (PID=246) to work on /opt/airflow/dags/my_dag.py
[2024-07-05T01:33:13.402+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-07-05T01:33:13.412+0000] {logging_mixin.py:188} INFO - [2024-07-05T01:33:13.411+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-07-05T01:33:17.951+0000] {processor.py:840} INFO - DAG(s) 'exchange_rate_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-07-05T01:33:18.000+0000] {logging_mixin.py:188} INFO - [2024-07-05T01:33:17.998+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-05T01:33:18.061+0000] {logging_mixin.py:188} INFO - [2024-07-05T01:33:18.058+0000] {dag.py:3954} INFO - Setting next_dagrun for exchange_rate_dag to 2024-04-09 00:00:00+00:00, run_after=2024-04-10 00:00:00+00:00
[2024-07-05T01:33:18.136+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 4.762 seconds
[2024-07-05T01:33:57.853+0000] {processor.py:161} INFO - Started process (PID=300) to work on /opt/airflow/dags/my_dag.py
[2024-07-05T01:33:57.868+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-07-05T01:33:57.888+0000] {logging_mixin.py:188} INFO - [2024-07-05T01:33:57.887+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-07-05T01:34:26.397+0000] {processor.py:840} INFO - DAG(s) 'exchange_rate_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-07-05T01:35:07.260+0000] {processor.py:186} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 182, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 163, in _handle_dag_file_processing
    result: tuple[int, int] = dag_file_processor.process_file(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 859, in process_file
    serialize_errors = DagFileProcessor.save_dag_to_db(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 115, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 895, in save_dag_to_db
    import_errors = DagBag._sync_to_db(dags=dags, processor_subdir=dag_directory, session=session)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 664, in _sync_to_db
    for attempt in run_with_db_retries(logger=log):
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 435, in __iter__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 368, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 410, in exc_check
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 183, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 677, in _sync_to_db
    _serialize_dag_capturing_errors(dag, session, processor_subdir)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 642, in _serialize_dag_capturing_errors
    dag_was_updated = SerializedDagModel.write_dag(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/serialized_dag.py", line 158, in write_dag
    if session.scalar(
       ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1747, in scalar
    return self.execute(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-07-05T01:36:14.182+0000] {processor.py:161} INFO - Started process (PID=36) to work on /opt/airflow/dags/my_dag.py
[2024-07-05T01:36:14.184+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-07-05T01:36:14.188+0000] {logging_mixin.py:188} INFO - [2024-07-05T01:36:14.187+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-07-05T01:36:25.900+0000] {processor.py:840} INFO - DAG(s) 'exchange_rate_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-07-05T01:36:26.363+0000] {logging_mixin.py:188} INFO - [2024-07-05T01:36:26.362+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-05T01:36:27.880+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 13.706 seconds
[2024-07-05T01:37:01.969+0000] {processor.py:161} INFO - Started process (PID=105) to work on /opt/airflow/dags/my_dag.py
[2024-07-05T01:37:02.070+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-07-05T01:37:02.073+0000] {logging_mixin.py:188} INFO - [2024-07-05T01:37:02.072+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-07-05T01:37:08.222+0000] {processor.py:840} INFO - DAG(s) 'exchange_rate_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-07-05T01:37:08.612+0000] {logging_mixin.py:188} INFO - [2024-07-05T01:37:08.612+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-05T01:37:08.697+0000] {logging_mixin.py:188} INFO - [2024-07-05T01:37:08.696+0000] {dag.py:3954} INFO - Setting next_dagrun for exchange_rate_dag to 2024-04-18 00:00:00+00:00, run_after=2024-04-19 00:00:00+00:00
[2024-07-05T01:37:09.251+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 7.292 seconds
[2024-07-05T01:37:40.209+0000] {processor.py:161} INFO - Started process (PID=179) to work on /opt/airflow/dags/my_dag.py
[2024-07-05T01:37:40.284+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-07-05T01:37:40.324+0000] {logging_mixin.py:188} INFO - [2024-07-05T01:37:40.305+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-07-05T01:38:12.870+0000] {logging_mixin.py:188} INFO - [2024-07-05T01:38:12.868+0000] {timeout.py:68} ERROR - Process timed out, PID: 179
[2024-07-05T01:38:49.540+0000] {processor.py:161} INFO - Started process (PID=251) to work on /opt/airflow/dags/my_dag.py
[2024-07-05T01:38:49.542+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-07-05T01:38:49.545+0000] {logging_mixin.py:188} INFO - [2024-07-05T01:38:49.544+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-07-05T01:38:54.524+0000] {processor.py:840} INFO - DAG(s) 'exchange_rate_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-07-05T01:38:54.940+0000] {logging_mixin.py:188} INFO - [2024-07-05T01:38:54.938+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-05T01:38:55.083+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 5.560 seconds
[2024-07-05T01:39:00.828+0000] {processor.py:161} INFO - Started process (PID=261) to work on /opt/airflow/dags/my_dag.py
[2024-07-05T01:39:00.834+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-07-05T01:39:00.838+0000] {logging_mixin.py:188} INFO - [2024-07-05T01:39:00.836+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2024-07-05T01:39:05.094+0000] {processor.py:840} INFO - DAG(s) 'exchange_rate_dag' retrieved from /opt/airflow/dags/my_dag.py
[2024-07-05T01:39:07.055+0000] {logging_mixin.py:188} INFO - [2024-07-05T01:39:07.032+0000] {taskinstance.py:2907} ERROR - {'DAG Id': 'exchange_rate_dag', 'Task Id': 'run_script', 'Run Id': 'scheduled__2024-04-17T00:00:00+00:00', 'Hostname': 'e26a552f405a', 'External Executor Id': '2bdcbc4d-77be-40d2-a658-0dba7eaa0349'}
[2024-07-05T01:39:07.175+0000] {logging_mixin.py:188} INFO - [2024-07-05T01:39:07.175+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=exchange_rate_dag, task_id=run_script, run_id=scheduled__2024-04-17T00:00:00+00:00, execution_date=20240417T000000, start_date=20240705T013358, end_date=20240705T013907
[2024-07-05T01:39:07.311+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: exchange_rate_dag.run_script scheduled__2024-04-17T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2024-07-05T01:39:07.363+0000] {logging_mixin.py:188} INFO - [2024-07-05T01:39:07.360+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-05T01:39:07.527+0000] {logging_mixin.py:188} INFO - [2024-07-05T01:39:07.519+0000] {dag.py:3954} INFO - Setting next_dagrun for exchange_rate_dag to 2024-04-20 00:00:00+00:00, run_after=2024-04-21 00:00:00+00:00
[2024-07-05T01:39:07.608+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 6.834 seconds
[2024-07-05T01:39:40.586+0000] {processor.py:161} INFO - Started process (PID=282) to work on /opt/airflow/dags/my_dag.py
[2024-07-05T01:39:40.597+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2024-07-05T01:39:40.615+0000] {logging_mixin.py:188} INFO - [2024-07-05T01:39:40.613+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
